### ISSUE TITLE
[BUG] Newly added insurances/person does not sync with current list

### ISSUE THREAD

**Issue by Juxarius** [CS2103AUG2017-T13-B1/main#138]
So if we identify people by name, if i add Oscar who is in an insurance, the insurance should link to him (he is newly added).

FIXED: Now it re-syncs everytime a person is added or deleted

*New Bug: A deleted person can still be accessed if an insurance used to be linked to him

**Comment by OscarWang114** [comment]
Small request:
Can I start fixing it after merging your PR since it contains important changes?

**Comment by Juxarius** [comment]
yes pls do that cos my PR includes the small quick fix
