### ISSUE TITLE
code quality comments for arnollim

### ISSUE THREAD

**Issue by okkhoy** [CS2103AUG2017-T13-B1/main#161]
![image](https://user-images.githubusercontent.com/1023494/32653534-309fbf0a-c643-11e7-8dbe-f614781a272f.png)
- don't retain commented out code

![image](https://user-images.githubusercontent.com/1023494/32653549-3d99c12e-c643-11e7-9970-45016e685f21.png)
- remove such comments that don't add any additional value

@arnollim FYA

**Comment by arnollim** [comment]
Thank you Akshay for the review. I have already remove these commented out code on Thursday after v1.5rc in my own repository. Had been pushing the cleanup till v1.5 to focus on features.
